[aftermuseum_exhibition]
title = "널 위한 문화예술 ─ 전시"
url = "https://www.sixshop.com/aftermuseum/exhibition"
entrySelector = "div.productListPage.productListPage-1.now div.shopProductWrapper.badgeUse"
titleSelector = "div.shopProduct.productName"
linkSelector = "a"
contentSelector = "div.shopProduct.price span:nth-child(1)"
imageSelector = "div.thumbDiv div.thumb.img"
waitUntil = "networkidle"